### ISSUE TITLE
First try, AttributeError: 'str' object has no attribute 'read' in parser.py, line 162

### ISSUE THREAD

**Issue by honoref** [geographika/mappyfile#52]
Hello, 
I want to convert my mapfiles in json to queries them with jq...

I do a simple example, just a load, with a mapserver.map in the same directory (full access on it), 
**root@d40f7c90b3d7:/shells# head ./mapserver.map**
```
MAP
    CONFIG  "MS_ERRORFILE" "/var/log/mapserver/error.log"
    NAME "test"
    EXTENT  -357823.2365 6037008.6939 1313632.3628 7230727.3772
    PROJECTION
        "init=epsg:2154"
    END
    DEBUG 4
```
**root@d40f7c90b3d7:/shells# cat displaymapfile.py**
```
import mappyfile
mapfile = mappyfile.load("./mapserver.map")
```
-----

**root@d40f7c90b3d7:/shells# python displaymapfile.py**
```
Traceback (most recent call last):
  File "displaymapfile.py", line 2, in <module>
    mapfile = mappyfile.load("./mapserver.map")
  File "/usr/local/lib/python2.7/site-packages/mappyfile/utils.py", line 59, in load
    ast = p.load(fp)
  File "/usr/local/lib/python2.7/site-packages/mappyfile/parser.py", line 162, in load
    text = fp.read()
AttributeError: 'str' object has no attribute 'read'

```
I try with python 2.7 and python 3.5 (docker images) and install mappyfile with pip

Where's my mistake ?

BR,

**Comment by honoref** [comment]
with mappyfile.open it's OK.
